name: release
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Release version (e.g. v0.1.0)'
                required: true
            message:
                description: 'Tag message'
                required: true
jobs:
    build:
        strategy:
            matrix:
                java: [ 16 ]
        runs-on: ubuntu-latest
        env:
            PUBLISH_SUFFIX: releases
        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: setup jdk ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}

            - name: make gradle wrapper executable
              run: chmod +x ./gradlew

            - name: capture build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Artifacts
                  path: build/libs/

            - name: publish
              run: ./gradlew publish

            - name: Create Tag
              uses: christophebedard/tag-version-commit@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
