name: release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The version to release, e.g. '1.0.0'
        type: string

jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
    runs-on: ubuntu-latest
    env:
      PUBLISH_SUFFIX: releases
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: publish
        run: ./gradlew publish

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/Artifacts.zip
          asset_name: Artifacts.zip
          asset_content_type: application/zip
      - uses: eregon/publish-release@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
